### ISSUE TITLE
Offline File Store Crashes

### ISSUE THREAD

**Issue by MNUser69** [lostindark/DriverStoreExplorer#114]
DSE crashes when trying to use an offline file store. I cloned my boot drive and have the cloned drive temporarily attached as drive "H" on my running system. I choose to use the offline file store and point the path to:

H:\Windows\System32\DriverStore\FileRepository

Note- I've also tried H:\Windows\System32\DriverStore\

Here is the error:

************** Exception Text **************
Microsoft.Dism.DismException (0x80070003): An error occurred. No operation was performed.
Verify that DISM is installed properly in the image, and then try the operation again.
at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
at Microsoft.Dism.DismSession.Reload()
at Microsoft.Dism.DismSession..ctor(String imagePath, String windowsDirectory, String systemDrive)
at Microsoft.Dism.DismApi.OpenSession(String imagePath, String windowsDirectory, String systemDrive)
at Microsoft.Dism.DismApi.OpenOfflineSession(String imagePath, String windowsDirectory, String systemDrive)
at Microsoft.Dism.DismApi.OpenOfflineSession(String imagePath)
at Rapr.Utils.DismUtil.EnumeratePackages() in **C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 49**
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__14.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rapr.DSEForm.<ChooseDriverStoreToolStripMenuItem_Click>d__38.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 874
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************

I bolded the line that I think is the problem. Directory "C:\projects\driverstoreexplore" doesn't exist on my computer and I'm wondering if its a path left over from your build that is wrong.   Crash occurs under Windows 7

**Comment by lostindark** [comment]
You need to choose the folder which include the windows folder. In this case, H:\.

I've made a fix so that the error should not crash DSE now 346f6b8a918bf17d9377acf33e524e196389a683.
