### ISSUE TITLE
Error when trying to delete x86 printer drivers on an x64 Windows 2016

### ISSUE THREAD

**Issue by RobertOnGit** [lostindark/DriverStoreExplorer#150]
On Windows Server the printer drivers are often installed twice, so that both x86 and x64 client Windows systems can successfully pull a driver. The 'Select old driver' works fine, deleting the x64 drivers work fine, but deleting the x86 driver cause an error:

```
2020-11-25 10:29:00Z [Error]: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) in C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:line 147
   at Rapr.Utils.DismUtil.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 152
2020-11-25 10:29:00Z [Information]: Deletion of momud.inf (oem17.inf) failed.
```

**Comment by lostindark** [comment]
Is the x86 driver still present after delete the x64 driver?

**Comment by RobertOnGit** [comment]
Hmm... good question.
The nature is that Windows Server OS will only show x64 itself. The easy test would be to try to point&print install on a x86 client Windows OS. Unfortunately I've go rid of the last x86 VM after Win7 went out of support and I haven't replaced it by a new x86 client VM.
When I look in the DriverStore FileRepository the x86 files are still there.
