### ISSUE TITLE
error deleting intel "old" driver

### ISSUE THREAD

**Issue by jonhp** [lostindark/DriverStoreExplorer#151]
i did not try force as the error is "unknown". not sure force is the correct next step. - jon

2020-11-30 15:13:23Z [Information]: Deletion of ibtusb.inf (oem26.inf) succeeded.
2020-11-30 15:13:23Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   at Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) in C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:line 147
   at Rapr.Utils.DismUtil.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 152

**Comment by lostindark** [comment]
ERROR_INF_IN_USE (0xE000023D). Try force delete the driver if you're sure it is not used.
