### ISSUE TITLE
The request is not supported

### ISSUE THREAD

**Issue by Silverman925** [lostindark/DriverStoreExplorer#201]
I run the 'Driver Store Explorer' and immediately the green bar starts moving and within a second an error box opens and states 'The request is not supported'.....  I click OK and it states in the middle of the page 'No entries loaded' also at the bottom of the page a red bar appears and again 'The request is not supported' is stated.  The same happens if I click 'Refresh', I tried to load the contents of the INF and and get the same.

I'm running Win 10 x64 Home edition

Here is the complete contents of your log:

   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 248
2022-09-10 19:35:04Z [Information]: Shutting down - reason UserClosing
2022-09-10 19:39:26Z [Information]: ---------------------------------------------------------------
2022-09-10 19:39:26Z [Information]: Rapr started
2022-09-10 19:39:26Z [Information]: Scanning driver store...
2022-09-10 19:39:26Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 248
2022-09-10 19:41:18Z [Information]: Scanning driver store...
2022-09-10 19:41:19Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 248
2022-09-10 19:51:32Z [Information]: Scanning driver store...
2022-09-10 19:51:33Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 248
2022-09-10 19:55:30Z [Information]: Scanning driver store...
2022-09-10 19:55:31Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 248
2022-09-10 19:59:32Z [Information]: Adding driver package...
2022-09-10 19:59:34Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<ButtonAddDriver_Click>d__20.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 449
2022-09-10 19:59:48Z [Information]: Adding driver package...
2022-09-10 19:59:49Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<ButtonAddDriver_Click>d__20.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 449
2022-09-10 19:59:54Z [Information]: Scanning driver store...
2022-09-10 19:59:56Z [Error]: Microsoft.Dism.DismException (0x80070002): The request is not supported.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Microsoft.Dism.DismApi.OpenOnlineSession()
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 248

**Comment by lostindark** [comment]
Please try latest version and see if it is fixed. Reopen if you have a repro.
