### ISSUE TITLE
Exception in About page on link clicked

### ISSUE THREAD

**Issue by PrOF-kk** [lostindark/DriverStoreExplorer#215]
Help > About > Click any link
Translated error message is "File not found"
<details><summary>Exception details</summary>
<p>

```
************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Impossibile trovare il file specificato
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Rapr.AboutBox.TextBoxDescription_LinkClicked(Object sender, LinkClickedEventArgs e) in C:\projects\driverstoreexplorer\Rapr\AboutBox.cs:line 175
   at System.Windows.Forms.RichTextBox.OnLinkClicked(LinkClickedEventArgs e)
   at System.Windows.Forms.RichTextBox.EnLinkMsgHandler(Message& m)
   at System.Windows.Forms.RichTextBox.WmReflectNotify(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Rapr
    Assembly Version: 0.11.92.0
    Win32 Version: 0.11.92
    CodeBase: file:///E:/tools/DriverStoreExplorer.v0.11.92/Rapr.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 0.11.92
    CodeBase: file:///E:/tools/DriverStoreExplorer.v0.11.92/Rapr.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.Dism
    Assembly Version: 1.0.0.0
    Win32 Version: 0.11.92
    CodeBase: file:///E:/tools/DriverStoreExplorer.v0.11.92/Rapr.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 0.11.92
    CodeBase: file:///E:/tools/DriverStoreExplorer.v0.11.92/Rapr.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
```

</p>
</details>

**Comment by JonnyTech** [comment]
Did you extract all of the folders from the .zip file? Looks like your language is Italian so make sure that the folder `it-IT` is present.

**Comment by lostindark** [comment]
This error usually means your system don't know how to open the URL. Likely some configuration issue or registry corruption. See below on how to fix it.
https://g.co/gemini/share/c9bca31b372a
