### ISSUE TITLE
"An error occurred. No operation was performed. Verify that DISM is installed properly in the image, and then try the operation again"...

### ISSUE THREAD

**Issue by MrTatiTunes** [lostindark/DriverStoreExplorer#222]
I guess that some part of programs and some utilities always look for system components in C:\ drive... unfortunately my systems are never on C:\ so this error is invoked by looking for DISM to open offline Driver Storage and fails.
O this error is something else...
Please help.

**Comment by MrTatiTunes** [comment]
LOG
2023-05-02 11:15:03Z [Information]: ---------------------------------------------------------------
2023-05-02 11:15:03Z [Information]: Rapr started
2023-05-02 11:15:04Z [Information]: Scanning driver store...
2023-05-02 11:15:06Z [Information]: Ready
2023-05-02 11:16:11Z [Information]: Scanning driver store...
2023-05-02 11:16:11Z [Error]: Microsoft.Dism.DismException (0x80070003): An error occurred. No operation was performed.
Verify that DISM is installed properly in the image, and then try the operation again.
   at Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   at Microsoft.Dism.DismSession.Reload()
   at Rapr.Utils.DismUtil.GetSession() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 128
   at Rapr.Utils.DismUtil.EnumeratePackages() in C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() in C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:line 249
2023-05-02 11:16:43Z [Information]: Scanning driver store...
2023-05-02 11:16:45Z [Information]: Ready
2023-05-02 11:17:24Z [Information]: Skanowanie magazynu sterowników...
2023-05-02 11:17:26Z [Information]: Gotowy
2023-05-02 11:17:41Z [Information]: Skanowanie magazynu sterowników...
2023-05-02 11:17:43Z [Information]: Gotowy
2023-05-02 11:24:01Z [Information]: Wybrano 10 sterownik(i/ów). Rozmiar całkowity: 23 MB.
oem25.inf - rtdusbad_gigabyte.inf_amd64_3021e8092634213a - 2 MB
oem67.inf - ibtusb.inf_amd64_da5167bdd66ed8f1 - 339 KB
oem68.inf - ibtusb.inf_amd64_e5e8fe77a64628b5 - 959 KB
oem69.inf - ibtusb.inf_amd64_4d9e3f3539995c76 - 269 KB
oem70.inf - ibtusb.inf_amd64_75a8b5996c3e6936 - 956 KB
oem71.inf - ibtusb.inf_amd64_8aae3a1998f645ec - 1 MB
oem72.inf - ibtusb.inf_amd64_6900e70ac508b885 - 6 MB
oem73.inf - ibtusb.inf_amd64_22673e44b16160b5 - 5 MB
oem74.inf - ibtusb.inf_amd64_d489b73b779a7f16 - 2 MB
oem75.inf - ibtusb.inf_amd64_c06ea043b768c34d - 4 MB
2023-05-02 11:26:09Z [Information]: Skanowanie magazynu sterowników...
2023-05-02 11:26:09Z [Error]: Microsoft.Dism.DismException (0x80070003): An error occurred. No operation was performed.
Verify that DISM is installed properly in the image, and then try the operation again.
   w Microsoft.Dism.DismUtilities.ThrowIfFail(Int32 hresult, DismSession session, String callerMemberName)
   w Microsoft.Dism.DismSession.Reload()
   w Rapr.Utils.DismUtil.GetSession() w C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:wiersz 128
   w Rapr.Utils.DismUtil.EnumeratePackages() w C:\projects\driverstoreexplorer\Rapr\Utils\DismUtil.cs:wiersz 80
   w System.Threading.Tasks.Task`1.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Rapr.DSEForm.<PopulateUIWithDriverStoreEntries>d__16.MoveNext() w C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:wiersz 249
2023-05-02 11:36:55Z [Information]: Shutting down - reason UserClosing
2023-05-02 11:36:55Z [Information]: Shutting down - reason UserClosing

**Comment by MrTatiTunes** [comment]
https://github.com/lostindark/DriverStoreExplorer/issues/116 
It was solved with instruction to point only Drive of Windows installation, not further system folders.
/o\

**Comment by PB0019c** [comment]
how to fix?
