### ISSUE TITLE
Support for removing Extensions App Devices

### ISSUE THREAD

**Issue by FadeMind** [lostindark/DriverStoreExplorer#67]
DCH drivers provides new type of "device" = Extensions. Sadly CMDLINE app (pnputil) and DSE cannot handle it at all. 

Sample: 
```
hdbusext.inf - Intel DCH Audio Extension driver INF. 
```

```
C:\WINDOWS\system32>pnputil.exe /delete-driver oem33.inf /force
Microsoft PnP Utility

Failed to delete driver package: There are currently one or more devices installed using the specified INF file.

C:\WINDOWS\system32>
```

![scr-1558379493-001](https://user-images.githubusercontent.com/9846948/58045805-dd757b00-7b43-11e9-9b82-0d7111871b43.png)

BTW. DDU handle whole intel mess extept this INF.

**Comment by lostindark** [comment]
Can you try if this works?
pnputil.exe /delete-driver oem33.inf /uninstall

**Comment by FadeMind** [comment]
I had same issue with `OSFDisk Virtual Adapter` aaand 
`pnputil.exe /delete-driver oem40.inf /uninstall` do the job. Thanks. 
![scr-1562784109-001](https://user-images.githubusercontent.com/9846948/60995628-29c68580-a353-11e9-85b1-954ae88f372e.png)

**Comment by lostindark** [comment]
Implemented the uninstall logic. Please try this version and see if it works for you.
https://ci.appveyor.com/api/buildjobs/eaavs60esyvknse0/artifacts/Rapr%2Fbin%2FDriverStoreExplorer.v0.10.47.zip

**Comment by FadeMind** [comment]
@lostindark did not works well.
![scr-1563173691-001](https://user-images.githubusercontent.com/9846948/61199554-b0c28780-a6de-11e9-9929-3b6bf7089fa5.png)
Only console cmd works.

**Comment by lostindark** [comment]
Can you share the log file?

**Comment by FadeMind** [comment]
You can reproduce this issue in your OS by downloading and installing https://www.osforensics.com/tools/mount-disk-images.html 
After purge driver via `pnputil.exe /delete-driver oem40.inf /uninstall` unknown device still present in Device Manager). 
What type of LOGS you want? :>

**Comment by lostindark** [comment]
I mean driver explorer logs. I'll try repro tonight.

**Comment by FadeMind** [comment]
@lostindark i forgot about major thing. In APP OSFMount you need create a sample RAM disk or just mount any supported image, next simple remove them (image). Otherwise DRIVER will be not installed in OS.

**Comment by lostindark** [comment]
I tried repro and DSE can delete driver correctly (with force option).
The unknown device present is the correct behavior. DSE won't remove devices. It is the app's job to remove devices it creates.

**Comment by lostindark** [comment]
Also, seems OSFMount is not using DCH drivers. They looks like different issue to me.

**Comment by FadeMind** [comment]
@lostindark OK, I downloaded lastest Intel UHD DCH drivers from station drivers (INF INST) and only one driver cannot be deleted via DSE. 
IGCC from igcc_dch.inf. 

BUT IN CMD works well.

![s](https://i.imgur.com/DE80zFO.png)

AND mainly i found log 😉 (Why some words are translated from ENGLISH to POLISH like **wiersz = line and w = in**?) 

```
2019-07-09 05:04:05Z [Information]: Rapr started
2019-07-09 05:04:27Z [Information]: Deleting drive 	r package(s)...
2019-07-09 05:04:27Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 144
2019-07-09 05:04:27Z [Error]: Error removing osfdisk.inf (oem40.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]
2019-07-09 05:05:01Z [Information]: Shutting down - reason UserClosing
```

```
2019-07-20 10:41:14Z [Information]: ---------------------------------------------------------------
2019-07-20 10:41:14Z [Information]: Rapr started
2019-07-20 10:41:56Z [Information]: Deleting driver package(s)...
2019-07-20 10:41:56Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.TraceWin32ErrorMessage(Boolean result) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 341
2019-07-20 10:41:56Z [Error]: Error removing igcc_dch.inf (oem48.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]

```
Full log



```
2019-07-09 05:04:05Z [Information]: ---------------------------------------------------------------
2019-07-09 05:04:05Z [Information]: Rapr started
2019-07-09 05:04:27Z [Information]: Deleting driver package(s)...
2019-07-09 05:04:27Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   in Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) in C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:line 144
2019-07-09 05:04:27Z [Error]: Error removing osfdisk.inf (oem40.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]
2019-07-09 05:05:01Z [Information]: Shutting down - reason UserClosing
2019-07-09 17:10:20Z [Information]: ---------------------------------------------------------------
2019-07-09 17:10:20Z [Information]: Rapr started
2019-07-09 17:10:39Z [Information]: Deleting driver package(s)...
2019-07-09 17:10:40Z [Information]: Removed nvami.inf (oem12.inf) from driver store
2019-07-09 17:10:55Z [Information]: Shutting down - reason UserClosing
2019-07-10 14:02:45Z [Information]: ---------------------------------------------------------------
2019-07-10 14:02:45Z [Information]: Rapr started
2019-07-10 14:03:26Z [Information]: Shutting down - reason UserClosing
2019-07-10 18:37:26Z [Information]: ---------------------------------------------------------------
2019-07-10 18:37:26Z [Information]: Rapr started
2019-07-10 18:37:40Z [Information]: Deleting driver package(s)...
2019-07-10 18:37:40Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 144
2019-07-10 18:37:40Z [Error]: Error removing osfdisk.inf (oem40.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]
2019-07-10 18:42:55Z [Information]: Ready
2019-07-10 18:43:57Z [Information]: Shutting down - reason UserClosing
2019-07-10 18:51:40Z [Information]: ---------------------------------------------------------------
2019-07-10 18:51:40Z [Information]: Rapr started
2019-07-10 18:56:06Z [Information]: Shutting down - reason UserClosing
2019-07-11 14:13:08Z [Information]: ---------------------------------------------------------------
2019-07-11 14:13:08Z [Information]: Rapr started
2019-07-11 14:13:38Z [Information]: Shutting down - reason UserClosing
2019-07-12 10:22:46Z [Information]: ---------------------------------------------------------------
2019-07-12 10:22:46Z [Information]: Rapr started
2019-07-12 10:22:57Z [Information]: Selected 1 Driver(s). Total size: 118 KB.
2019-07-12 10:22:57Z [Information]: Selected 2 Driver(s). Total size: 39 MB.
2019-07-12 10:22:57Z [Information]: Selected 3 Driver(s). Total size: 44 MB.
2019-07-12 10:22:57Z [Information]: Selected 4 Driver(s). Total size: 48 MB.
2019-07-12 10:23:14Z [Information]: Deleting driver package(s)...
2019-07-12 10:23:14Z [Information]: Deletion of hdx_asusext_ice_rtk.inf (oem22.inf) succeeded.
2019-07-12 10:23:16Z [Information]: Deletion of hdxasus.inf (oem46.inf) succeeded.
2019-07-12 10:23:17Z [Information]: Deletion of realtekapo.inf (oem52.inf) succeeded.
2019-07-12 10:23:17Z [Information]: Deletion of realtekservice.inf (oem54.inf) succeeded.
2019-07-12 10:23:17Z [Information]: Removed 4 packages from driver store
2019-07-12 10:23:35Z [Information]: Shutting down - reason UserClosing
2019-07-12 17:32:33Z [Information]: ---------------------------------------------------------------
2019-07-12 17:32:33Z [Information]: Rapr started
2019-07-12 17:38:20Z [Information]: Shutting down - reason UserClosing
2019-07-13 07:25:21Z [Information]: ---------------------------------------------------------------
2019-07-13 07:25:21Z [Information]: Rapr started
2019-07-13 07:28:44Z [Information]: Shutting down - reason UserClosing
2019-07-14 06:16:08Z [Information]: ---------------------------------------------------------------
2019-07-14 06:16:08Z [Information]: Rapr started
2019-07-14 06:16:23Z [Information]: Contents saved to D:\fademind\Desktop\c.csv. Export Completed.
2019-07-14 06:44:07Z [Information]: Shutting down - reason UserClosing
2019-07-14 06:44:49Z [Information]: ---------------------------------------------------------------
2019-07-14 06:44:49Z [Information]: Rapr started
2019-07-14 07:08:10Z [Information]: Shutting down - reason UserClosing
2019-07-15 06:49:24Z [Information]: ---------------------------------------------------------------
2019-07-15 06:49:24Z [Information]: Rapr started
2019-07-15 06:52:12Z [Information]: Ready
2019-07-15 06:53:07Z [Information]: Deleting driver package(s)...
2019-07-15 06:53:07Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.TraceWin32ErrorMessage(Boolean result) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 341
2019-07-15 06:53:07Z [Error]: Error removing osfdisk.inf (oem22.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]
2019-07-15 06:54:04Z [Information]: Shutting down - reason UserClosing
2019-07-15 06:54:08Z [Information]: ---------------------------------------------------------------
2019-07-15 06:54:08Z [Information]: Rapr started
2019-07-15 06:54:25Z [Information]: Deleting driver package(s)...
2019-07-15 06:54:25Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.TraceWin32ErrorMessage(Boolean result) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 341
2019-07-15 06:54:25Z [Error]: Error removing osfdisk.inf (oem22.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]
2019-07-15 06:55:46Z [Information]: Ready
2019-07-15 06:56:24Z [Information]: Deleting driver package(s)...
2019-07-15 06:56:24Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.TraceWin32ErrorMessage(Boolean result) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 341
2019-07-15 06:56:25Z [Error]: Error removing osfdisk.inf (oem22.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]
2019-07-15 06:57:00Z [Information]: Ready
2019-07-15 06:57:15Z [Information]: Shutting down - reason UserClosing
2019-07-15 06:59:51Z [Information]: ---------------------------------------------------------------
2019-07-15 06:59:51Z [Information]: Rapr started
2019-07-15 07:02:06Z [Information]: Shutting down - reason UserClosing
2019-07-15 11:29:44Z [Information]: ---------------------------------------------------------------
2019-07-15 11:29:44Z [Information]: Rapr started
2019-07-15 11:30:19Z [Information]: Shutting down - reason UserClosing
2019-07-17 05:09:26Z [Information]: ---------------------------------------------------------------
2019-07-17 05:09:26Z [Information]: Rapr started
2019-07-17 05:10:18Z [Information]: Shutting down - reason UserClosing
2019-07-17 10:49:53Z [Information]: ---------------------------------------------------------------
2019-07-17 10:49:53Z [Information]: Rapr started
2019-07-17 10:50:13Z [Information]: Deleting driver package(s)...
2019-07-17 10:50:18Z [Information]: Removed x542uf_305.inf (oem29.inf) from driver store
2019-07-17 10:50:42Z [Information]: Shutting down - reason UserClosing
2019-07-17 16:08:06Z [Information]: ---------------------------------------------------------------
2019-07-17 16:08:06Z [Information]: Rapr started
2019-07-17 16:08:51Z [Information]: Deleting driver package(s)...
2019-07-17 16:08:54Z [Information]: Removed x542uf_304.inf (oem29.inf) from driver store
2019-07-17 16:09:01Z [Information]: Shutting down - reason UserClosing
2019-07-17 17:44:44Z [Information]: ---------------------------------------------------------------
2019-07-17 17:44:44Z [Information]: Rapr started
2019-07-17 17:45:11Z [Information]: Shutting down - reason UserClosing
2019-07-20 08:06:53Z [Information]: ---------------------------------------------------------------
2019-07-20 08:06:53Z [Information]: Rapr started
2019-07-20 08:07:05Z [Information]: Selected 1 Driver(s). Total size: 914 MB.
2019-07-20 08:07:05Z [Information]: Selected 2 Driver(s). Total size: 932 MB.
2019-07-20 08:07:05Z [Information]: Selected 3 Driver(s). Total size: 932 MB.
2019-07-20 08:07:05Z [Information]: Selected 4 Driver(s). Total size: 1 GB.
2019-07-20 08:07:05Z [Information]: Selected 5 Driver(s). Total size: 1 GB.
2019-07-20 08:07:25Z [Information]: Deleting driver package(s)...
2019-07-20 08:07:26Z [Information]: Deletion of iigd_dch.inf (oem20.inf) succeeded.
2019-07-20 08:07:27Z [Information]: Deletion of cui_dch.inf (oem47.inf) succeeded.
2019-07-20 08:07:27Z [Information]: Deletion of hdbusext.inf (oem49.inf) succeeded.
2019-07-20 08:07:27Z [Information]: Deletion of msdk.inf (oem50.inf) succeeded.
2019-07-20 08:07:29Z [Information]: Deletion of intcdaud.inf (oem59.inf) succeeded.
2019-07-20 08:07:29Z [Information]: Removed 5 packages from driver store
2019-07-20 08:08:22Z [Information]: Shutting down - reason UserClosing
2019-07-20 10:41:14Z [Information]: ---------------------------------------------------------------
2019-07-20 10:41:14Z [Information]: Rapr started
2019-07-20 10:41:56Z [Information]: Deleting driver package(s)...
2019-07-20 10:41:56Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   w Rapr.Utils.SetupAPI.TraceWin32ErrorMessage(Boolean result) w C:\projects\driverstoreexplorer\Rapr\Utils\SetupAPI.cs:wiersz 341
2019-07-20 10:41:56Z [Error]: Error removing igcc_dch.inf (oem48.inf) from driver store  [TIP: The driver may still being used. Try FORCE deleting the package]

```

**Comment by lostindark** [comment]
As I mentioned, you'll need to use "Force Deletion" option to delete DCH drivers.

**Comment by FadeMind** [comment]
@lostindark I will try when next Intel DCH will be released, anyway thanks for your help. Regards.

**Comment by lostindark** [comment]
Close issue as it should be fixed. Please reopen if you find a repro.

**Comment by koobs** [comment]
I have a reproduction with:

- DSE latest (`v0.12.110.0`) Mode: `DISM` and `pnputil`
- Windows 10 22H2 x64 (all updates)
- Canon MG5700 Series Printer Driver (mg5700p6.inf)

Attempted:

 - DISM: standard and forced delete (fails)
 - PNPUTIL: standard (fails) forced (succeeds)


## rapr.log (initial: DISM)

```
2025-09-01 06:12:13Z [Information]: Migrated UseNativeDriverStore setting: True -> DriverStoreOption: Native
2025-09-01 06:12:13Z [Information]: Settings migration completed successfully
2025-09-01 06:12:14Z [Information]: ---------------------------------------------------------------
2025-09-01 06:12:14Z [Information]: Rapr started
2025-09-01 06:12:14Z [Information]: Scanning driver store...
2025-09-01 06:12:16Z [Information]: Ready
2025-09-01 06:12:40Z [Information]: Scanning driver store...
2025-09-01 06:12:41Z [Information]: Ready
2025-09-01 06:12:58Z [Information]: Scanning driver store...
2025-09-01 06:13:39Z [Information]: Ready
2025-09-01 06:14:26Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:14:27Z [Information]: Selected 2 Driver(s). Total size: 92 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
oem62.inf - mg5700p6.inf_amd64_87a1a66a62ed04d8 - 46 MB
2025-09-01 06:14:35Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:14:40Z [Information]: Deleting driver package(s)...
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:14:40Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   at Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
   at Rapr.Utils.DismUtil.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
2025-09-01 06:15:04Z [Error]: Error removing mg5700p6.inf (oem39.inf) from driver store.
[TIP: The driver may still being used. Try FORCE deleting the package]
2025-09-01 06:15:11Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:15:18Z [Information]: Deleting driver package(s)...
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:15:21Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   at Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
   at Rapr.Utils.DismUtil.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
2025-09-01 06:15:50Z [Error]: Error removing mg5700p6.inf (oem39.inf) from driver store.
2025-09-01 06:16:04Z [Information]: Shutting down - reason UserClosing
```

## rapr.log (initial + pnputil)

```
2025-09-01 06:12:13Z [Information]: Migrated UseNativeDriverStore setting: True -> DriverStoreOption: Native
2025-09-01 06:12:13Z [Information]: Settings migration completed successfully
2025-09-01 06:12:14Z [Information]: ---------------------------------------------------------------
2025-09-01 06:12:14Z [Information]: Rapr started
2025-09-01 06:12:14Z [Information]: Scanning driver store...
2025-09-01 06:12:16Z [Information]: Ready
2025-09-01 06:12:40Z [Information]: Scanning driver store...
2025-09-01 06:12:41Z [Information]: Ready
2025-09-01 06:12:58Z [Information]: Scanning driver store...
2025-09-01 06:13:39Z [Information]: Ready
2025-09-01 06:14:26Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:14:27Z [Information]: Selected 2 Driver(s). Total size: 92 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
oem62.inf - mg5700p6.inf_amd64_87a1a66a62ed04d8 - 46 MB
2025-09-01 06:14:35Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:14:40Z [Information]: Deleting driver package(s)...
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:14:40Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   at Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
   at Rapr.Utils.DismUtil.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
2025-09-01 06:15:04Z [Error]: Error removing mg5700p6.inf (oem39.inf) from driver store.
[TIP: The driver may still being used. Try FORCE deleting the package]
2025-09-01 06:15:11Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:15:18Z [Information]: Deleting driver package(s)...
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:15:21Z [Error]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe000023d)
   at Rapr.Utils.SetupAPI.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
   at Rapr.Utils.DismUtil.DeleteDriver(DriverStoreEntry driverStoreEntry, Boolean forceDelete)
2025-09-01 06:15:50Z [Error]: Error removing mg5700p6.inf (oem39.inf) from driver store.
2025-09-01 06:16:04Z [Information]: Shutting down - reason UserClosing
2025-09-01 06:18:43Z [Information]: ---------------------------------------------------------------
2025-09-01 06:18:43Z [Information]: Rapr started
2025-09-01 06:18:43Z [Information]: Scanning driver store...
2025-09-01 06:19:07Z [Information]: Ready
2025-09-01 06:21:45Z [Information]: Scanning driver store...
2025-09-01 06:21:58Z [Information]: Ready
2025-09-01 06:22:27Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:22:46Z [Information]: Deleting driver package(s)...
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:22:47Z [Error]: Error removing mg5700p6.inf (oem39.inf) from driver store.
[TIP: The driver may still being used. Try FORCE deleting the package]
2025-09-01 06:22:52Z [Information]: Selected 1 Driver(s). Total size: 46 MB.
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:22:56Z [Information]: Deleting driver package(s)...
oem39.inf - mg5700p6.inf_amd64_0ce157b0c2526652 - 46 MB
2025-09-01 06:22:56Z [Information]: Removed mg5700p6.inf (oem39.inf) from driver store.
```
